[package]
name = "cherry"
version = "0.1.1"
authors = ["bugslabx <bugslabx@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/bugslabx/cherry"
keywords = ["orm", "database", "postgres", "mysql", "sqlite"]
description = "Simple orm base on sqlx, support mysql, postgres, sqlite and mssql."

[lib]
name = "cherry"

#[features]
#default = ["sqlx/default"]
#mysql = ["sqlx/mysql"]
#postgres = ["sqlx/postgres"]
#sqlite = ["sqlx/sqlite"]
#mssql = ["sqlx/mssql"]



[dependencies]
anyhow = "1.0.38"
thiserror = "1.0.30"
async-trait = "0.1.48"
once_cell = "1.7.0"

serde = "1.0.123"
serde_derive = "1.0.123"
sql-builder = "3.1.1"
sqlx = { version = "0.5.9", features = [ "runtime-async-std-rustls", "macros", "chrono", "json", "mysql", "mssql", "postgres", "sqlite" ]}

[dev-dependencies]
futures-await-test = "0.3.0"
cherry-derive = {package = "cherry-derive", path = "../cherry-derive"}
