[package]
name = "cherry"
version = "0.3.3"
authors = ["bugslabx <bugslabx@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/bugslabx/cherry"
keywords = ["ORM", "MySQL", "PostgreSQL", "SQLite", "SQLServer"]
description = "An asynchronous ORM, support MySQL, PostgreSQL, SQLite and SQL Server."

[lib]
name = "cherry"

[features]
default = ["sqlx/default"]
mysql = ["sqlx/mysql","cherry-macros/mysql"]
postgres = ["sqlx/postgres","cherry-macros/mysql"]
sqlite = ["sqlx/sqlite","cherry-macros/mysql"]
#mssql = ["sqlx/mssql"]

uuid = ["sqlx/uuid"]
json = ["sqlx/json", "serde", "serde_derive"]
time = ["sqlx/time"]
chrono = ["sqlx/chrono"]

macros = ["sqlx/sqlx-macros"]
bit-vec = ["sqlx/bit-vec"]
decimal = ["sqlx/decimal"]
bigdecimal = ["sqlx/bigdecimal"]
bstr = ["sqlx/bstr"]
git2 = ["sqlx/git2"]
ipnetwork = ["sqlx/ipnetwork"]
mac_address = ["sqlx/mac_address"]
migrate = ["sqlx/migrate"]
offline = ["sqlx/offline"]
tls = ["sqlx/tls"]

runtime-actix = ["sqlx/runtime-actix"]
runtime-actix-native-tls = ["sqlx/runtime-actix-native-tls"]
runtime-actix-rustls = ["sqlx/runtime-actix-rustls"]
runtime-async-std = ["sqlx/runtime-async-std"]
runtime-async-std-native-tls = ["sqlx/runtime-async-std-native-tls"]
runtime-async-std-rustls = ["sqlx/runtime-async-std-rustls"]
runtime-tokio = ["sqlx/runtime-tokio"]
runtime-tokio-native-tls = ["sqlx/runtime-tokio-native-tls"]
runtime-tokio-rustls = ["sqlx/runtime-tokio-rustls"]

#all = ["sqlx/all"]
#all-types = ["sqlx/all-types"]
#all-databases = ["sqlx/all-databases"]
#any = ["sqlx/any"]

[dependencies]
futures = "0.3"
anyhow = "1.0.38"
async-trait = "0.1.51"
once_cell = "1.7.0"
sql-builder = "3.1.1"
sqlx = "0.5.9"
serde = { version = "1.0.123", optional = true }
serde_derive = { version = "1.0.123", optional = true }


[dependencies.cherry-macros]
version = "0.7"

[dev-dependencies]
tokio = { version = "1.1", features = ["full"] }
anyhow = "1"
