[package]
name = "cherry-derive"
version = "0.1.0"
authors = ["bugslabx <bugslabx@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/bugslabx/cherry"
keywords = ["orm", "sqlx", "database", "async", "postgres", "mysql", "sqlite"]
description = "Simple orm base on sqlx, support mysql, postgres, sqlite and mssql."

[lib]
name = "cherry_derive"
proc-macro = true

[dependencies]
proc-macro2 = "1.0.26"
syn = "1.0.68"
quote = "1.0.10"
heck = "0.3.2"
